---
roles:
  - name: geerlingguy.apache
    src: https://github.com/geerlingguy/ansible-role-apache
    version: 4.0.0

  - src: https://github.com/benoistlaurent/ansible-role-dokuwiki.git
    version: 1.0.0

